config/routes.rb
Rails.application.routes.draw do

  root 'pastum#index'
  get 'pastum/new' => 'pastum#new'
  post 'pastum/new' =>'pastum#create'

end

app/models/pasta_type.rb
class PastaType < ActiveRecord::Base

  validates: :name, presence: true
end

app/models/pastum.rb
class Pastum < ActiveRecord::Base

  validates :name, presence: true
  validates :texture, presence: true
  validates :price, presence: true
  validates :color, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastum_controller.rb
class PastumController < ApplicationController

  # def destroy
  # end

  def create
  end

  # def update
  # end

  # def show
  # end

  def index
    @pasta = Pastum.all
  end

  def new
    @pastum = Pastum.new(pasta_params)
  end

  def pasta_params
    params.permit(:name, :texture, :color, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pastum_helper.rb
module PastumHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pastum/index.html.erb
<h1>PASTA TIME!</h1>
<% link_to("MAKE UR OWN!!!!", pastum_new_url) %>
<img src="http://globerove.com/wp-content/uploads/2010/03/Italian-chef-school.jpg">

app/views/pastum/new.html.erb
<%= form_tag("/pastum/create", method: "post") do %>
  <%= label_tag(:name, "Pasta Shape:") %>
  <%= text_field_tag(:name) %>

  <%= label_tag(:texture, "Pasta Texture:") %>
  <%= text_field_tag(:texture) %>

  <%= label_tag(:color, "Pasta Color:") %>
  <%= text_field_tag(:color) %>

  <%= label_tag(:price, "Pasta Price:") %>
  <%= number_field_tag(:price) %>


  <%= submit_tag("Make Pastum") %>
<% end %>